import type { SFSymbol } from "expo-symbols";

// SF Symbols draw natively on iOS. Android and the web build draw Material Symbols
// instead, so every SF Symbol the app uses needs a Material equivalent here.
export const MATERIAL: Partial<Record<SFSymbol, string>> = {
  "arrow.clockwise": "refresh",
  "arrow.up.right": "north_east",
  "arrowshape.turn.up.left.fill": "reply",
  "bell.badge.fill": "notifications_active",
  "building.columns": "account_balance",
  "building.columns.fill": "account_balance",
  checkmark: "check",
  "checkmark.circle.fill": "check_circle",
  "checkmark.seal.fill": "verified",
  "chevron.right": "chevron_right",
  circle: "radio_button_unchecked",
  "clock.fill": "schedule",
  "doc.text.magnifyingglass": "find_in_page",
  "dollarsign.circle.fill": "paid",
  "envelope.fill": "mail",
  "exclamationmark.triangle.fill": "warning",
  "hammer.fill": "build",
  "heart.fill": "favorite",
  "list.number": "format_list_numbered",
  "lock.fill": "lock",
  "lock.open.fill": "lock_open",
  magnifyingglass: "search",
  "paperplane.fill": "send",
  pencil: "edit",
  "person.2.fill": "group",
  "person.crop.circle": "account_circle",
  plus: "add",
  "questionmark.bubble.fill": "contact_support",
  "sparkle.magnifyingglass": "travel_explore",
  sparkles: "auto_awesome",
  "star.fill": "star",
  tray: "inbox",
  "tray.full": "inbox",
  xmark: "close",
  "xmark.circle.fill": "cancel",
};
